version: '3.8'

services:
  # The Brain (Runs everything in one container for simplicity in this version)
  soc-simulation:
    build: .
    image: soc-simulator:latest
    container_name: soc_lab_1
    volumes:
      # This maps your LOCAL logs folder to the CONTAINER'S logs folder
      # logic: ./local_path:/container_path
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1